---
- name: hosts.allow
  become: true
  ansible.builtin.template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    backup: 'yes'
    mode: 0644
    owner: root
    group: root

- name: hosts.deny
  become: true
  ansible.builtin.template:
    src: hosts.deny.j2
    dest: /etc/hosts.deny
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
...
