---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    lock_timeout: 600
  register: _apt_upgrade
  retries: 10
  delay: 15
  until: _apt_upgrade is succeeded

- name: Install basic tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
    lock_timeout: 600
  register: _apt_install
  retries: 10
  delay: 15
  until: _apt_install is succeeded

- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Fix /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"