---
- name: resolved.conf
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd

- name: resolv.conf
  become: true
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
